### ISSUE TITLE
Tutorial 3: missing data

### ISSUE THREAD

**Issue by kampelmuehler** [libigl/libigl-python-bindings#100]
All the example data for Tutorial 3 is not in the repository

https://github.com/libigl/libigl-python-bindings/blob/40be4c4fa5b8b77d37128b944883656d809d2444/tutorial/tut-chapter3.ipynb

**Comment by teseoch** [comment]
I checked some random and they are here:
https://github.com/libigl/libigl-tutorial-data

Which one is missing?

**Comment by alecjacobson** [comment]
The cmake will download the tutorial data, but this is an admittedly weird way to get it. Right now the data is downloaded _optionally_ during build. If someone installed with pip, e.g., and just wants to try out the tutorial then it's awkward to get the data. A couple ideas:

 - improve the cmake download scripts so that they can be called _without_ building the bindings,
 - download the tutorial data via python (e.g., `download_data_for_tutorial.py`), or
 - move the tutorial to a different repo

**Comment by kampelmuehler** [comment]
Thanks for taking care of this!
