### ISSUE TITLE
How to create .dmat files?

### ISSUE THREAD

**Issue by mirickmi** [libigl/libigl-python-bindings#143]
In chapter 1 (https://libigl.github.io/libigl-python-bindings/tut-chapter1/) under the section "Gradient" a .dmat file is read for the example mesh:
u = igl.read_dmat(os.path.join(root_folder, "data", "cheburashka-scalar.dmat"))

However, I don't know how to calculate "u" for my own mesh objects. 
Is there an easy formula or function to do so?

**Comment by alecjacobson** [comment]
`u` is a scalar value pre-vertex, so it's a #vertices vector of values. I think the one in that file is a Laplacian eigen mode (a smooth function on that specific surface). It's stored in the file rather than computed on the model on the fly so that the tutorial entry can focus on the gradient computation.
